"""add unique constraint for knowledge base name

Revision ID: 87f793799088
Revises: 80da663cc1dc
Create Date: 2025-05-20 22:36:49.722800

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87f793799088"
down_revision: Union[str, None] = "80da663cc1dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "knowledgebase", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "knowledgebase", type_="unique")
    # ### end Alembic commands ###
