"""add extraction status for document table

Revision ID: 985b26a331ab
Revises: 1deb6d1d71c7
Create Date: 2025-04-06 18:03:52.942644

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "985b26a331ab"
down_revision: Union[str, None] = "1deb6d1d71c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type in PostgreSQL
    # This is necessary to avoid issues with the ENUM type not being found
    postgresql.ENUM(
        "PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", name="extractionstatus"
    ).create(op.get_bind(), checkfirst=False)

    op.add_column(
        "document",
        sa.Column(
            "extraction_status",
            sa.Enum(
                "PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", name="extractionstatus"
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "extraction_status")

    postgresql.ENUM(
        "PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", name="extractionstatus"
    ).drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
