"""add user for knowledge base

Revision ID: d11eaf358878
Revises: c0644c46e6e5
Create Date: 2025-05-24 19:33:21.312090

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d11eaf358878"
down_revision: Union[str, None] = "c0644c46e6e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledgebase",
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.add_column(
        "knowledgebase", sa.Column("created_by_id", sa.Uuid(), nullable=False)
    )
    op.create_foreign_key(None, "knowledgebase", "user", ["created_by_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "knowledgebase", type_="foreignkey")
    op.drop_column("knowledgebase", "created_by_id")
    op.drop_column("knowledgebase", "description")
    # ### end Alembic commands ###
